apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "realtime-bridge.fullname" . }}-config
  labels:
    {{- include "realtime-bridge.labels" . | nindent 4 }}
  {{- if .Values.configMapAnnotations }}
  annotations:
    {{- toYaml .Values.configMapAnnotations | nindent 4 }}
  {{- end }}
data:
  OPENAI_API_BASE: {{ default "" .Values.env.config.openaiApiBase | quote }}
  OPENAI_API_MODEL: {{ default "" .Values.env.config.openaiApiModel | quote }}
  STT_API_BASE: {{ default "" .Values.env.config.sttApiBase | quote }}
  TTS_API_URL: {{ default "" .Values.env.config.ttsApiUrl | quote }}
  DEFAULT_VAD_START_MS: {{ default "" .Values.env.config.defaultVadStartMs | quote }}
  DEFAULT_VAD_END_MS: {{ default "" .Values.env.config.defaultVadEndMs | quote }}
  DEFAULT_VAD_PAD_MS: {{ default "" .Values.env.config.defaultVadPadMs | quote }}
  DEFAULT_VAD_MAX_MS: {{ default "" .Values.env.config.defaultVadMaxMs | quote }}
  DEFAULT_VAD_MIN_VOICE_MS: {{ default "" .Values.env.config.defaultVadMinVoiceMs | quote }}
  DEFAULT_VAD_AUTORESP: {{ default "" .Values.env.config.defaultVadAutoresp | quote }}
